name: postgres
builder:
  name: BalabitBuilder
  configure_options: >
    --enable-thread-safety
    --without-docdir
    --without-tcl
    --without-perl
    --without-python
    --without-krb5
    --without-pam
    --without-ldap
    --without-bonjour
    --without-openssl
    --without-readline
    --without-zlib
