name: postgres
builder:
  name: BalabitBuilder
  configure_options: "--enable-thread-safety --without-docdir --without-tcl --without-perl --without-python --without-krb5 --without-pam --without-ldap --without-bonjour --without-openssl --without-readline --without-zlib"
  flags: "no-make-dist"
platforms:
  - aix-6.1/powerpc
  - freebsd-9.2/amd64
  - freebsd-9.2/i386
  - freebsd-10.1/amd64
  - freebsd-10.1/i386
  - hpux-11v2/ia64
  - linux-glibc2.11/amd64
  - linux-glibc2.11/i386
  - linux-glibc2.3.6/amd64
  - linux-glibc2.3.6/i386
  - solaris-10/amd64
  - solaris-10/sparc
  - solaris-10/sparc64
  - solaris-11/amd64
  - solaris-11/sparc64 
  - ubuntu-bionic/amd64
